from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

# Adjust these imports based on your exact file structure
from apps.api.dependencies import get_db  # Your async session dependency
from storage.database.models import Asset, AssetOutput, ProcessingStatus

router = APIRouter(prefix="/assets", tags=["Observations"])

@router.get("/{asset_id}/observations")
async def get_asset_observation_graph(asset_id: str, db: AsyncSession = Depends(get_db)):
    """
    Fetches the decoupled observation graph (PPE, Equipment, Distances) 
    for a specific processed asset.
    """
    
    # 1. Check if the root asset actually exists
    asset = await db.get(Asset, asset_id)
    if not asset:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, 
            detail=f"Asset {asset_id} not found."
        )

    # 2. Query the exact output payload from the worker
    # Note: Using "vision_geometry" based on your worker.py implementation
    query = select(AssetOutput).where(
        AssetOutput.asset_id == asset_id,
        AssetOutput.output_type == "vision_geometry"
    )
    result = await db.execute(query)
    output_record = result.scalars().first()

    # 3. Handle asynchronous race conditions gracefully
    if not output_record:
        # If Celery hasn't finished yet, tell the frontend to poll again later
        if asset.processing_status in [ProcessingStatus.PENDING, ProcessingStatus.PROCESSING]:
            return {
                "asset_id": asset_id,
                "status": asset.processing_status.value,
                "message": "Asset is still processing. Check back soon.",
                "data": None
            }
        else:
            # If it failed or didn't produce vision data (e.g., it was an audio file)
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="No vision observation data found for this asset."
            )

    # 4. Return the pristine JSON payload
    return {
        "asset_id": asset_id,
        "status": asset.processing_status.value,
        "data": output_record.output_content  # This is the JSON generated by observation.py
    }